# Generated by Django 5.0.3 on 2024-03-23 20:12

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{6,12}$'), 'Пароль повинен мати довжину від 6 до 12 символів, містити малу і велику літеру та цифру.')])),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
    ]
