# Generated by Django 5.0.3 on 2024-04-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_jobposition_user_userjobposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobposition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
